### ISSUE TITLE
能否支持一些markdown高级语法？

### ISSUE THREAD

**Issue by wukaikailive** [mittsuu/MarkedView-for-Android#2]
如上下标等，能加入支持吗？

**Comment by mittsu333** [comment]
我很抱歉、我不会中文。
你写英語或日語？

**Comment by wukaikailive** [comment]
I am sorry. 
I found this MarkedView-for-Android does not support the super / subscript, you can consider adding support?

**Comment by mittsu333** [comment]
First of all, thank you very much for translating. I read though your messages and understood your request.

Regarding your inquiry, I am currently investigating possibilities to support Android version of 'superscript' and 'subscript' in the future, though I do NOT promise this at this point in time.

So please wait for the further notification!

**Comment by mittsu333** [comment]
Hi, @wukaikailive 
The supported of the super / subscript was kept in v1.0.3.
Please try.
[Release v1.0.3](https://github.com/mittsuu/MarkedView-for-Android/releases/tag/v1.0.3)

**Comment by wukaikailive** [comment]
Thanks a lot!
