### ISSUE TITLE
很大几率进去了MarkedView里显示空白

### ISSUE THREAD

**Issue by Jetereting** [mittsuu/MarkedView-for-Android#3]
同样的内容 有时进去行 有时候就渲染不出来了

**Comment by cozyplanes** [comment]
Translation in English : 
> The same content sometimes go in the line sometimes rendering out of the

**Comment by mittsu333** [comment]
@cozyplanes
Thank you very much for your translation.

@Jetereting, @cozyplanes
Because I'd like to fix it.
If you have the Markdown text, don't you tell me?
