### ISSUE TITLE
Issue when getting string from edittext and display that as md

### ISSUE THREAD

**Issue by cozyplanes** [mittsuu/MarkedView-for-Android#4]
I have markdown text written by user in edittext. But converting to string and loading in `mdView.setMDText(context)`, it doesnt show the render of the written text  
@mittsuu

**Comment by mittsu333** [comment]
I cannot reproduce it with my project, for me it works. 
Are you check difference in grammar? If not, can you explain how.

　

This result screenshot.

![screenshot_20170707-192633](https://user-images.githubusercontent.com/5404354/27968806-852fcdf8-6383-11e7-866b-43c321c85e8a.png)
![screenshot_20170707-192621](https://user-images.githubusercontent.com/5404354/27968807-883a755c-6383-11e7-9f36-3c742bf6dba9.png)

**Comment by cozyplanes** [comment]
Would you mind if you send the source of the below app you sent me with 
the screenshot?
Thanks.
Ian

@mittsuu please, fast reply will be thankful

------ Original Message ------

**Comment by mittsu333** [comment]
@cozyplanes 
I found some bugs related to this problem and I will fix it.
Sample source are also added when updating, please give me some time.

I will plan to respond by the weekend.

**Comment by mittsu333** [comment]
Hi, @cozyplanes 

Fixed bug and added sample code, so please look it.

[Release Note v1.0.5](https://github.com/mittsuu/MarkedView-for-Android/releases/tag/v1.0.5)
