### ISSUE TITLE
Why table is not supported?

### ISSUE THREAD

**Issue by jmimohsin** [mittsuu/MarkedView-for-Android#6]
I have checked closed issue as well but didn't get what to do. Table is not supported else everything is Good.

This one is supporting table: https://github.com/tiagohm/MarkdownView

Please let me know if this possible. Thanks.

**Comment by mittsu333** [comment]
@jmimohsin 
The supported of the table was in v1.0.6.
Please try.

**Comment by jmimohsin** [comment]
Working...thanks a lot.
