### ISSUE TITLE
Getting a manifest collision

### ISSUE THREAD

**Issue by hsson** [mittsuu/MarkedView-for-Android#7]
When trying to use this, I get a weird manifest collision:
```
Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:12:9-36
	is also present at [com.mittsu:markedview:1.0.6] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:10:5-69:19 to override.
```
I don't understand why this would happen in a library, never had this issue with any other third party library.

**Comment by mittsu333** [comment]
@hsson 
Sorry, My library had manifest was unnecessary code.
Deleted was problem xml tag, parameter.

Update to new version(v1.0.7) please try.

Thanks.
